[REFACTORING] MDN parboiled parser can be a constant
Instantiation of the parser was performed via reflection upon each MDN
parsing.

The instantiation of the parser generated several exception stack-traces
on one of our running production instance:

```
 java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.apache.james.mdn.MDNReportParser.parse(MDNReportParser.java:57)
	at org.apache.james.mdn.MDNReportParser.parse(MDNReportParser.java:53)
	at org.apache.james.jmap.mailet.ExtractMDNOriginalJMAPMessageId.parseReport(ExtractMDNOriginalJMAPMessageId.java:120)
[...]
Caused by: java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.ClassNode.<init>(Unknown Source)
	at org.parboiled.transform.ParserClassNode.<init>(ParserClassNode.java:43)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:39)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
```

Given that a parser only defines a set of rules, and is thus immutable,
we can turn it into a constant, effectively solving our problem.